baseurl = "www.rockandroh.com"
title = "Rock and Roh"
author = "Hyunwoo (Eric) Roh"
canonifyurls = true
languagecode = "en"
paginate = 3
theme = "hugo-renga"

enableEmoji = true
hasCJKLanguage = true

# googleAnalytics = "UA-00000000-1"
# disqusShortname = "your-disqus-shortname"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

#[permalinks]
#post = "/:year/:month/:day/:slug/"

[params]
pagetitle = "Rock and Roh"
author = "Hyunwoo (Eric) Roh"
copyright = "© 2020 Roh"
copyrightUrl = "/"
description = "This site includes technical notes, data set, and paper reviews"
faviconfile = "image/favicon.png"
logofile = "image/avatar.jpg"
posts_navigation = true
uselatex = true
highlightjs = true
progressively = false

github = "HW-Roh"
#twitter = "eri"
#linkedin = "nanxstats"
email = "metrics@kakao.com"
medium = "corr.roh"
contact = "/contact/"
support = "/support/"
subscribe = "/subscribe/"
latestpostcount = 7

#[[params.best_posts]]
#title = "Graphics in R with ggplot2"
#url = "/blog/graphics-in-r-with-ggplot2/"

[[menu.primary]]
identifier = "note"
name = "Note"
url = "/note/"
weight = 1

[[menu.primary]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.primary]]
identifier = "cv"
name = "CV"
url = "/cv/"
weight = 3

[[menu.primary]]
identifier = "data"
name = "data"
url = "/data/"
weight = 4

[[menu.primary]]
identifier = "research"
name = "Research"
url = "/research/"
weight = 5

[[menu.primary]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 6

[params.info]
related = true # Includes related articles at the bottom of the article

[related]
    threshold = 0 
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "date"
        weight = 10


